version: '3.8'
networks:
  traefik:
    driver: overlay
    name: traefik
    external: true

services:
  registry:
    image: registry:2
    networks:
      - traefik
    environment:
      - REGISTRY_STORAGE=s3
      - REGISTRY_STORAGE_S3_REGION=eu-west-2
      - REGISTRY_STORAGE_S3_BUCKET=docker-image-registry-xvfbnm
      - REGISTRY_STORAGE_S3_ACCESSKEY=${ACCESS_KEY}
      - REGISTRY_STORAGE_S3_SECRETKEY=${SECRET_KEY}
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "256M"
        reservations:
          cpus: "0.25"
          memory: "128M"
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.labels.type==batch"
      update_config:
        parallelism: 1
        delay: 15s
        monitor: 5s
        failure_action: rollback
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.routers.registry.rule=Host(`registry.glpapps.com`)"
        - "traefik.http.routers.registry.service=registry"
        - "traefik.http.routers.registry.entrypoints=web"
        - "traefik.http.routers.registry.middlewares=redirect-https"
        - "traefik.http.routers.registry-secure.tls=true"
        - "traefik.http.routers.registry-secure.rule=Host(`registry.glpapps.com`)"
        - "traefik.http.routers.registry-secure.entrypoints=websecure"
        - "traefik.http.routers.registry-secure.middlewares=auth"
        - "traefik.http.routers.registry-secure.tls.certresolver=letsencrypt"
        - "traefik.http.routers.registry-secure.tls.domains[0].main=glpapps.com"
        - "traefik.http.routers.registry-secure.tls.domains[0].sans=*.glpapps.com"
        - "traefik.http.routers.registry-secure.service=registry"
        - "traefik.http.services.registry.loadbalancer.server.port=5000"
